### ISSUE TITLE
Broken Icons

### ISSUE THREAD

**Issue by ModdedGamers** [Donnnno/Arcticons#114]
I have been using this, and these icons do not display properly. Please fix this!

```
<!-- Aurora Store -->
<item component="ComponentInfo{com.aurora.store/com.aurora.store.view.ui.onboarding.OnboardingActivity}" drawable="aurorastore"/>
<!-- Authenticator -->
<item component="ComponentInfo{me.jmh.authenticatorpro/crc643c2a2b888a14ec9a.MainActivity}" drawable="authenticator"/>
<!-- DuckDuckGo -->
<item component="ComponentInfo{com.duckduckgo.mobile.android/com.duckduckgo.app.launch.LauncherBlack}" drawable="duckduckgo"/>
<!-- SystemUI Tuner -->
<item component="ComponentInfo{com.zacharee1.systemuituner/com.zacharee1.systemuituner.MainActivity}" drawable="systemuituner"/>
<!-- Telegram X -->
<item component="ComponentInfo{org.thunderdog.challegram/org.thunderdog.challegram.MainActivity}" drawable="telegramx"/>
<!-- Weather -->
<item component="ComponentInfo{wangdaye.com.geometricweather/wangdaye.com.geometricweather.main.MainActivity}" drawable="weather"/>

```

**Comment by dalaeance** [comment]
A note on DDG: It won't work if you're using one of DDG's custom icons, which I'm guessing you are based on the `LauncherBlack` bit in the code.

I suppose Donno could add a line for each of DDG's built-in custom icon colours, so people not realizing this don't open issues.

I only know this because the same thing happened to me, but the realization popped into my head right before I included it in an icon request. I probably should've mentioned it then.

**Comment by ModdedGamers** [comment]
Thanks for mentioning that. That's good to know!

**Comment by Donnnno** [comment]
Fixed the remaining broken icons!
