### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by coxackie** [Donnnno/Arcticons#128]
[20210415_025050.zip](https://github.com/Donnnno/Arcticons/files/6316464/20210415_025050.zip)

mostly games - no t sure how much interested you are in doing these. Note that Archero should only contain the arrow (and not the bottom-left temporary character). Once again, great work!

**Comment by Donnnno** [comment]
I'll take a look at it when I have some time :)

**Comment by Donnnno** [comment]
Here are most of the icons, game icons are mostly hard to do, so I simplified some. If you don't want to see the other icons I didn't make, you could create a folder with the foldergames icon & put everything in there :)

![image](https://user-images.githubusercontent.com/31142286/115997558-c539f080-a5e3-11eb-88be-2948caabd1d2.png)
![image](https://user-images.githubusercontent.com/31142286/115997618-04684180-a5e4-11eb-931d-22be9f8e9bbb.png)

And as always, consider donating because creating these icons can cost a lot of time, and star the project. Thanks :^)

**Comment by coxackie** [comment]
many thanks. 💯 

 not sure exactly how to make a folder with a specific icon, but I will look at it. I usually just drag and drop an icon on another and this automatically creates a folder.

**Comment by Donnnno** [comment]
Hi, took some time to create the last five icons, they will be in the next update ;) 

![image](https://user-images.githubusercontent.com/31142286/116819768-c9c95080-ab71-11eb-9aa4-9fcf18781f1d.png)
