### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by ajay230ps** [Donnnno/Arcticons#138]
@`
[Icon_Request.txt](https://github.com/Donnnno/Arcticons/files/6411710/Icon_Request.txt)
`

**Comment by Donnnno** [comment]
Hi, Can you use the Turtl app to collect the information needed to create the icons? I can't do anything with this information.

There's a more detailed explanation in the README :)

**Comment by ajay230ps** [comment]
Hi I have used the  turtl app for icon request. Once selected it only copied things on the clipboard.

I'll  check again

**Comment by Donnnno** [comment]
You have to use the second option, that one collects the icon png files too.

**Comment by ajay230ps** [comment]
Got it my bad. I clicked on other key.

Here is the zip file. 
[20210502_092704.zip](https://github.com/Donnnno/Arcticons/files/6411752/20210502_092704.zip)

**Comment by Donnnno** [comment]
No problem :) I'll take a look when I have some time.

**Comment by Donnnno** [comment]
Wanted to release a new update so created a bunch of icons.
Some icons did already exist, so I updated them so that they work again in the next update.
There's one game icon I skipped because it is too complicated to make: freefire. I used a standard letter icon for that one (letterf.svg)

Here's a preview of the new icons:

![image](https://user-images.githubusercontent.com/31142286/116825584-39e6cf00-ab90-11eb-91de-a54ed77b754f.png)
![image](https://user-images.githubusercontent.com/31142286/116825587-3c492900-ab90-11eb-8299-f3f5bada1440.png)
![image](https://user-images.githubusercontent.com/31142286/116825589-3fdcb000-ab90-11eb-9af8-ffacc6c97434.png)
![image](https://user-images.githubusercontent.com/31142286/116825591-423f0a00-ab90-11eb-92ab-b15a77bedaf3.png)

Ps. if you like them and want to support this icon pack, consider leaving a few bucks & star it on GitHub :) It can be very time-consuming to do this, thanks :^)
