### ISSUE TITLE
Email parser doesn't filter out added entries

### ISSUE THREAD

**Issue by Donnnno** [Donnnno/Arcticons#1691]
The email parser script is great, but it doesn't filter out the recent added entries in the appfilter:

Whenever I run the script, it adds entries it recognizes to a list called updatable, but a lot of the times it adds entries that have been added to the appfilter already. So a lot of time goes into checking if it's really in there.

**Comment by Donnnno** [comment]
for example, this entry has been added recently, but it still shows up in the updatable file

![image](https://github.com/Donnnno/Arcticons/assets/31142286/26fbc49b-2b41-464d-928d-48442a7e1af7)

**Comment by Kaiserdragon2** [comment]
At the moment the script does not delete entries that exist in the appfilter file from the request.txt instead it checks if an entry with the same package name exists. If so this is added to the updateable.
I would change the script so that similar entries are deleted from the request.txt and everything else is checked if a similar packagename is already in the appfilter. If so it will be added to the updateable.

**Comment by Donnnno** [comment]
That would be awesome! Just updated the whole list, it costed me more than one hour 🙃 ~200 entires are checked now tho

**Comment by Kaiserdragon2** [comment]
With this change there also would be no need to manually delete listings from the request file this could help prevent merge conflicts

**Comment by Donnnno** [comment]
Wow sick!
