### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by TBog** [Donnnno/Arcticons#1790]
2023-11-10 06:02:56,899 ERROR: Could not build app com.donnnno.arcticons.you: Some glob paths did not match any files/dirs:freedesktop-theme/arcticons.tar.gz

**Comment by Donnnno** [comment]
Oof, maybe< @autinerd knows how to fix that?

**Comment by autinerd** [comment]
I don't know how the F-Droid stuff works, but here https://gitlab.com/fdroid/fdroiddata/-/blob/581133ceed4c44f253bc2d0533abc84fba0b9e8a/metadata/com.donnnno.arcticons.yml (and also the other versions of arcticons) is in line 692--693:
```yaml
    rm:
      - freedesktop-theme/arcticons.tar.gz
```
which is no longer needed because the file no longer exists since 8.0.6.

But I have no clue on how to report this to F-Droid that it gets changed.

**Comment by Donnnno** [comment]
Created a new issue in the F-Droid repo: https://gitlab.com/fdroid/fdroiddata/-/issues/3128

**Comment by Donnnno** [comment]
The issue has been fixed!
