### ISSUE TITLE
Icon size?

### ISSUE THREAD

**Issue by MikeTheGreat** [Donnnno/Arcticons#1867]
I _think_ that all my icons were resized from 48x48 to 150x150px in my recent PR (https://github.com/Donnnno/Arcticons/pull/1841#event-11325927218).  (Except for one or two that were other, *cough* clearly wrong *cough*, sizes :( )

I'm fine with the resizing, but wanted to clarify if we should be making 150x150px icons (in which case should the contributing.md file be updated (at https://github.com/Donnnno/Arcticons/blob/main/CONTRIBUTING.md).

If not - can I ask why the icons get resized from 48x48 to 150x150?

(and/or - am I missing something?  It's entirely possible I'm making a mistake here :) )

**Comment by Donnnno** [comment]
Hi! Mike, I had to take a look for this, because I had to resize it, but I found the issue.

We use an artboard size of 48**px**, but I noticed that your documents were in millimeters instead of pixels. So what looked like the correct size for you, wasn't actually the case for me when I was checking it.

<img width="257" alt="Scherm­afbeelding 2023-12-23 om 12 55 32" src="https://github.com/Donnnno/Arcticons/assets/31142286/3fa647e7-6ead-4e25-b126-c339797d08f8"> → <img width="263" alt="Scherm­afbeelding 2023-12-23 om 12 55 18" src="https://github.com/Donnnno/Arcticons/assets/31142286/dc2245ac-9a2f-4178-ac89-9893075a6b3d">

Check your program's unit preferences, and change them to px, that should do the trick. (the template files have the correct measurements, so you can use those as a start too!)

**Comment by MikeTheGreat** [comment]
Whoops! Sorry about that and thank you for your patience and help!

**Comment by Donnnno** [comment]
No problem at all! It can be pretty confusing at times 😅
