### ISSUE TITLE
F-Droid uses the Material You version for everything.

### ISSUE THREAD

**Issue by Donnnno** [Donnnno/Arcticons#1878]
>com.donnnno.arcticons.you:126 - [web](https://f-droid.org/packages/com.donnnno.arcticons.you/) - [metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/0829a417e53c33a3fc797351dbcb4db618a3b4e8/metadata/com.donnnno.arcticons.you.yml) - [log](https://monitor.f-droid.org/builds/log/com.donnnno.arcticons.you/126#site-footer)
com.donnnno.arcticons:126 - [web](https://f-droid.org/packages/com.donnnno.arcticons/) - [metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/0829a417e53c33a3fc797351dbcb4db618a3b4e8/metadata/com.donnnno.arcticons.yml) - [log](https://monitor.f-droid.org/builds/log/com.donnnno.arcticons/126#site-footer)
com.donnnno.arcticons.light:126 - [web](https://f-droid.org/packages/com.donnnno.arcticons.light/) - [metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/0829a417e53c33a3fc797351dbcb4db618a3b4e8/metadata/com.donnnno.arcticons.light.yml) - [log](https://monitor.f-droid.org/builds/log/com.donnnno.arcticons.light/126#site-footer)
com.donnnno.arcticons.daynight:126 - [web](https://f-droid.org/packages/com.donnnno.arcticons.daynight/) - [metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/0829a417e53c33a3fc797351dbcb4db618a3b4e8/metadata/com.donnnno.arcticons.daynight.yml) - [log](https://monitor.f-droid.org/builds/log/com.donnnno.arcticons.daynight/126#site-footer)

Interesting that Dark, Light and You are now named 'Material You' with the same Icon as well in the App (both F-Droid and Droid-ify)

_Originally posted by @TotallyAvailable in https://github.com/Donnnno/Arcticons/issues/1799#issuecomment-1869479200_

**Comment by Donnnno** [comment]
![Screenshot_20231226_124124_F-Droid.jpg](https://github.com/Donnnno/Arcticons/assets/31142286/c84bede8-a2d2-414f-9e17-68346ed78f17)

🤔

**Comment by petlyh** [comment]
It looks like F-Droid depends on the flavor directories being named the same as the flavors. Therefore it, for example, looks for the `black` flavor metadata in `app/src/black/play/`, which doesn't exist since its metadata is in `app/src/light/play/` instead. Because it doesn't exist, F-Droid reads metadata from all the flavor directories in order, making the last one (`you`) effective.

The flavor directories need to be renamed to match the flavor names post-Renamening. I can create a PR for it if you'd like.

Source for the F-Droid behavior:  
https://gitlab.com/fdroid/fdroidserver/-/blob/master/fdroidserver/update.py#L806

**Comment by Donnnno** [comment]
Oh thank you for figuring it out! If you're able to create a pr, that would be amazing!

**Comment by petlyh** [comment]
> If you're able to create a pr, that would be amazing!

Will do. Do you mind if I update the dashboard titles to reflect the new names as well while I'm at it? I assume it's not supposed to be like this:

<img width="300" src="https://github.com/Donnnno/Arcticons/assets/88139840/77a7d0bf-e455-442a-b1d2-7acaaae64a02">

**Comment by Donnnno** [comment]
OOps, may have missed those! Thanks, go ahead :)
