### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by avtkal** [Donnnno/Arcticons#194]
Could you make an icon for these two apps? Thank you in advance!
```
<!-- Daily Dozen -->
<item component="ComponentInfo{org.nutritionfacts.dailydozen/org.nutritionfacts.dailydozen.activity.MainActivity}" drawable="dailydozen"/>
<!-- Food Tracker -->
<item component="ComponentInfo{org.secuso.privacyfriendlyfoodtracker/org.secuso.privacyfriendlyfoodtracker.ui.SplashActivity}" drawable="foodtracker"/>
```
![dailydozen](https://user-images.githubusercontent.com/63205014/122095411-a1d63980-ce0d-11eb-8fc6-fac66733e2f7.png)
![foodtracker](https://user-images.githubusercontent.com/63205014/122095416-a3076680-ce0d-11eb-9072-c81cfd74ac13.jpg)

**Comment by Donnnno** [comment]
Created the icons for your request!
I made the food tracker kinda minimalistic because the icon had too many elements.
Enjoy:

![image](https://user-images.githubusercontent.com/31142286/122390368-32c62580-cf72-11eb-90b9-5d4cf1a30eac.png)

Ps. if you like them and want to support this icon pack, consider leaving a few bucks & star it on GitHub :) It can be very time-consuming to do this, thanks :^)
