### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by Suburbanno** [Donnnno/Arcticons#248]
1. Catogram
2. Picpay
3. Flamingo
4. Cittamobi
5. Cinexplore
6. Castro
7. Catogram
8. Nubank
9. Grasshopper
10. League+
11. Moovit
12. XiaomiWear
13. Redditoria
14. Orna
15. Hypocam
16. StreetView
17. Press
18. Greenroom
19. Wild Rift
20. Catan WorldExplores
21. GalaxyStore
22. Game Launcher
23. Team Ward
24. Space Now
25. Samsung Pass
26. Samsung Pay Mini
27. Santander

of course, thank u so much for ur work, support you soon!
[20210808_090511.zip](https://github.com/Donnnno/Arcticons/files/6951661/20210808_090511.zip)

**Comment by Donnnno** [comment]
- [x]     Catogram
- [ ]     Picpay
- [x]     Flamingo
- [x]     Cittamobi
- [x]     Cinexplore
- [ ]     Castro
- [ ]     Catogram
- [ ]     Nubank
- [ ]     Grasshopper
- [x]     League+
- [ ]     Moovit
- [ ]     XiaomiWear
- [ ]     Redditoria
- [ ]     Orna
- [ ]     Hypocam
- [ ]     StreetView
- [ ]     Press
- [ ]     Greenroom
- [ ]     Wild Rift
- [ ]     Catan WorldExplores
- [x]     GalaxyStore
- [x]     Game Launcher
- [ ]     Team Ward
- [ ]     Space Now
- [ ]     Samsung Pass
- [ ]     Samsung Pay Mini
- [ ]     Santander

**Comment by Donnnno** [comment]
Hi, that was one of the bigger requests I've gotten here. But I've had some time today to create the icons. 

Here's a preview:

![image](https://user-images.githubusercontent.com/31142286/128789826-7d93c33a-48d0-414c-994b-b04cb5a1dc51.png)
![image](https://user-images.githubusercontent.com/31142286/128789834-884758e7-c7c1-4828-b94b-6742e5019d60.png)
![image](https://user-images.githubusercontent.com/31142286/128789841-2544b386-85cb-41da-8438-baae7572d13e.png)
![image](https://user-images.githubusercontent.com/31142286/128789849-e4fa84aa-9a3e-4cb4-944c-5a98567e4b86.png)

(I didn't create a Wild Rift icon, probably gonna use the letter 'w' there because characters are really hard to do with only lines.)

**Comment by Suburbanno** [comment]
thanks for this!!!
