### ISSUE TITLE
Line Colors Selection Option

### ISSUE THREAD

**Issue by mubashir-rehman** [Donnnno/Arcticons#403]
Inspired by #394 , I would suggest adding a feature to select a custom color for icon pack lines instead of Blue, White and Black.
I can think of two ways to achieve that.

- One is to generate all the files with newly selected colors on device. This can be extremely complicated and resource hungry but UX would be better.
- Other is to create an automatic system to generate custom apk files per user request in a seperate repo. This can be seen in action on https://github.com/nikgapps/config .

**Comment by Donnnno** [comment]
Hi, this is a kind of request that's been around since the beginning, see: #37

Generating files would be a huge task for a phone and probably way to complicated to do.

I have to take a better look at the nikgapps config thing to understand that, but let's move to the conversation to the original issue.

**Comment by mubashir-rehman** [comment]
Duplicate of #37
