### ISSUE TITLE
1.40 crashes + still missing icon ...

### ISSUE THREAD

**Issue by michas0602** [Donnnno/Arcticons#75]
Hi, I recently installed 1.40 and still dont see the "Verkaufen auf Etsy" Icon
(request #47)
![Screenshot_20210224-183029_Arcticons-01](https://user-images.githubusercontent.com/29848666/109041915-da6fcd00-76cf-11eb-9215-51f036ee67da.jpeg)

Furthermore 1.40 now crashes if I open the app and scroll to the bottom of the icons.
![Screenshot_20210224-183003_Arcticons](https://user-images.githubusercontent.com/29848666/109041665-9381d780-76cf-11eb-93aa-334c3a52f7f3.png)

The search bar also shows 1 Etsy-symbol only, nothing when searching for "Verkaufen".

**Comment by Donnnno** [comment]
Hi, I'm aware of the crash and fixed it already, it's not super important right now bc it's somewhere at the bottom.

I don't know what causes the verkaufen auf Etsy from working, so I don't know what to do about that. 
Right now I'm using the same icon as the regular Etsy icon, so that's why there is only one icon in there.

You can always try to select the icon manually, some launchers allow stuff like that.

**Comment by Donnnno** [comment]
Fixed the bug, icon request is now in: #79
