### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by RyuKurisu** [Donnnno/Arcticons#97]
<item component="ComponentInfo{cgeo.geocaching/cgeo.geocaching.SplashActivity}" drawable="cgeo"/>

The icon available for c:geo doesn't apply when using version 1.3.5 from F-Droid, I haven't checked the most recent 1.4.6 version.

**Comment by Donnnno** [comment]
Hi can you follow the icon request guide? Otherwise I can't help you :) 

**Icon Requests**

This app doesn't have an icon request feature, so you'll have to do the following steps.

    Install Turtl which can extract the icons and class names of your apps.
    Grant the storage access permission to Turtl in your system settings, this will allow it to save the zip file (Only required in Android 6 "Marshmallow" or newer, older versions grant this permission on installation).
    Open Turtl and follow the process to save the new zip file to your phone.
    Make an issue titled "Icon Request" and attach the zip file.

If Turtl is not working on your device, you can also use Applications Info or any equivalent app to collect the package name of the app ($PACKAGE_NAME) and the main activity name of the app ($ACTIVITY_NAME) launchable in Applications Info with no errors. Work is being done to simplify this process.

**Comment by RyuKurisu** [comment]
c:geo
item component="ComponentInfo{cgeo.geocaching/cgeo.geocaching.SplashActivity}" drawable="cgeo"

The above got commented out by accident.  It is an icon already added to Arcticons ~3 months ago: https://github.com/Donnnno/Arcticons/blob/main/icons/cgeo.svg

**Comment by Donnnno** [comment]
fixed it!

**Comment by RyuKurisu** [comment]
Thanks for the 1.4.6 release.  How can I install it to check if it is fixed?  I've only seen 2 archives attached, no apk.

**Comment by Donnnno** [comment]
Yea that's true because 1.4.6 adds nothing new it's just a fix for F-Droid.
